export const SAVE_POSTS = "SAVE_POSTS"
export const LOAD_MORE = "LOAD_MORE"
export const SET_LOADING = "SET_LOADING"
export const RESET_LOADING = "RESET_LOADING"
export const SET_ERROR = "SET_ERROR"
export const RESET_ERROR = "RESET_ERROR"